### ISSUE TITLE
部件无法拆分出复合体

### ISSUE THREAD

**Issue by 2664703791** [hanzi-chai/hanzi-chai.github.io#43]
![iShot_2023-12-23_下午10 20 05](https://github.com/hanzi-chai/hanzi-chai.github.io/assets/23151857/1bb8ff22-bf84-4347-8694-c897e9758d30)
“舍”是部件，“古”是复合体且被添加为元素的情况下，“舍”无法自动拆出“人一根+古”。

**Comment by tansongchen** [comment]
在 https://github.com/hanzi-chai/hanzi-chai.github.io/commit/39fd98fe90adb331a62f3e46f297dadc1f95072b 中修复
