### ISSUE TITLE
元素约束在约定约束开启后不生效

### ISSUE THREAD

**Issue by 2664703791** [hanzi-chai/hanzi-chai.github.io#45]
将字根“1”元素约束到“当前按键”“fi”，同时将“1”的第一码绑定约束到“亚”的第二码，此时“1”并没有如预期固定在fi上。

**Comment by tansongchen** [comment]
最新版已经实现了「部分归并」功能替代原有「绑定约束」功能，稍后 libchai 也会支持部分归并，可以开始在前端进行迁移了
