### ISSUE TITLE
复合体笔顺序列无法识别

### ISSUE THREAD

**Issue by mokapsing** [hanzi-chai/hanzi-chai.github.io#47]
![image](https://github.com/hanzi-chai/libchai/assets/39441028/d0db5a71-deca-403e-9e0b-557631603bf0)

![image](https://github.com/hanzi-chai/libchai/assets/39441028/718999b8-883a-40cf-99b9-bcfef08c1f03)

**Comment by tansongchen** [comment]
已经查明是「渊字边」这个复合体的数据有问题，笔顺应为「第 1 部 1 笔」+「第 2 部剩余」+「第 1 部剩余」，而不是「第 3 部」。已修复 https://github.com/hanzi-chai/hanzi-chai.github.io/commit/0851566f76e80b9fc1a73343d96915e382a34da6
