### ISSUE TITLE
字符集扩充至 CJK 基本集

### ISSUE THREAD

**Issue by Marksusu** [hanzi-chai/hanzi-chai.github.io#51]
试用了一下，希望能拆解更多繁、简和异体字，但没找到在哪里添加更多单字。

**Comment by tansongchen** [comment]
目前只支持 8105 字集，CJK 基本集正在制作中。

**Comment by tansongchen** [comment]
CJK 基本集和扩展 A 已完成，目前系统能拆近两万八千字。短期内应该不会继续扩大字集了

**Comment by Marksusu** [comment]
> CJK 基本集和扩展 A 已完成，目前系统能拆近两万八千字。短期内应该不会继续扩大字集了

已经很够用了，谢谢
